### ISSUE TITLE
Container height jump to height of next component

### ISSUE THREAD

**Issue by Nikoflash** [marnusw/react-css-transition-replace#25]
Hi there,

I was struggling with this problem for a while until I noticed this at the bottom of your very helpful page :) 

_If the .*-height class (or transitionName.height) is not specified the change in container height will not be animated but instead jump to the height of the entering component instantaneously._

Still I'm not sure what to do here. It's happening on the carousel-swap, and I've tried going my css file and setting .carousel-swap { height: <someHeight> }, but is that the way to go about it? I'm not sure either what the *-height class is? :)

Hope you can help!

- Nikoflash

**Comment by marnusw** [comment]
If you set up your `replace` container like this:

```javascript
<ReactCSSTransitionReplace transitionName="carousel-swap" transitionEnterTimeout={500} transitionLeaveTimeout={500}>
  {someChangingKeyedContent}
</ReactCSSTransitionReplace>
```

Then you will need CSS transitions like this:

```css
.carousel-swap-leave {
  transition: transform .3s ease-in-out;
  transform: translate(0, 0);
}
.carousel-swap-leave-active {
  transform: translate(-100%, 0);
}

.carousel-swap-enter {
  transition: transform .3s ease-in-out;
  transform: translate(100%, 0);
}
.carousel-swap-enter-active {
  transform: translate(0, 0);
}

.carousel-swap-height {
  transition: height .3s ease-in-out;
}
```

You create the animation the same as you would with `react-css-transition-group` with `*-enter` and `*-leave` styles, and then add an additional `*-height` style to animate the `transition: height`. If that transition isn't animated with CSS the height changes instantaneously.

I'm not sure if I understood your question correctly, so let me know if you're doing the above and still have the issue.
