### ISSUE TITLE
Transition are not putting 'enter' class into element, only 'enter-active'

### ISSUE THREAD

**Issue by renatorib** [marnusw/react-css-transition-replace#41]
![image](https://cloud.githubusercontent.com/assets/3277185/23530891/9b59f0e6-ff82-11e6-950d-23a12d0c3d83.png)

As you can see above, the appearing element have class `CrossFade-enter-active`, but don't have `CrossFade-enter` class, causing the appearing element not fade (it appears as 100% opacity, while the other fade correctly to disappear), see below.

![bug-replace](https://cloud.githubusercontent.com/assets/3277185/23531152/c9c35d7c-ff83-11e6-9397-7115a615828a.gif)

I really don't know what is causing this.

### My setup:

Usage:
```jsx
<Replace
  transitionName="CrossFade"
  transitionEnterTimeout={1000}
  transitionLeaveTimeout={1000}
>
  {renderMethod()}
</Replace>
```
Note: `renderMethod` return a div with unique `key`

CSS:
```css
.CrossFade-leave {
  opacity: 1;
}

.CrossFade-leave.CrossFade-leave-active {
  opacity: 0;
  transition: opacity 1s ease-in;
}

.CrossFade-enter {
  opacity: 0;
}

.CrossFade-enter.CrossFade-enter-active {
  opacity: 1;
  transition: opacity 1s ease-in;
}

.CrossFade-height {
  transition: height 500ms ease-in-out;
}
```
