### ISSUE TITLE
ReactCSSTransitionReplace with react-router v4 Bug?

### ISSUE THREAD

**Issue by romanlex** [marnusw/react-css-transition-replace#49]
Hello. I think what found bug. When animation is start I see next route not current.
![image](https://user-images.githubusercontent.com/3369304/28030036-c65dd756-65aa-11e7-8052-e0e038f5e74b.png)
On screen you can see two Switch with child Route. In first Switch with ref "curr" you can see Login Route and in last Switch with ref "next" you can see Login route.
It is bug or somewhing else?
I have this jsx:
```javascript
<ReactCSSTransitionReplace
	component="div"
	className="transition-wrapper"
	transitionName="wq-fadeOutLeft"
	transitionEnterTimeout={10000}
	transitionLeaveTimeout={10000}>
	<Switch key={location.pathname} location={location}>
	{
		routes && routes.length > 0 ?
			routes.map(({component: Component, ...rest}, index) => (
				<Route key={location.key} {...rest}
				       render={matchProps => (
					       <Component {...matchProps} routes={rest.routes} />
				       )}
				/>)
			)
			: ''
	}
	</Switch>
</ReactCSSTransitionReplace>
```
and css:
```css
.wq-fadeOutLeft-leave {
	opacity: 1;
}
.wq-fadeOutLeft-leave.wq-fadeOutLeft-leave-active {
	opacity: 0;
	transition: opacity 10s ease-in, transform 10s ease-in-out;
	transform: translate3d(-500px, 0, 0);
}

.wq-fadeOutLeft-enter {
	opacity: 0.01;
	transform: translate3d(500px, 0, 0);
}
.wq-fadeOutLeft-enter.wq-fadeOutLeft-enter-active {
	opacity: 1;
	transition: opacity 10s ease-in, transform 10s ease-in-out;
	transform: translate3d(0, 0, 0);
}
```
